### ISSUE TITLE
Too Many Device Photos

### ISSUE THREAD

**Issue by raulaltosaar** [jekynewage/jekynewage.github.io#1]
I am pushing the site to S3 and it is pushing a bunch of unused device photos. Removing these photos would make this theme a lot lighter. Thanks a lot!

**Comment by antoniotrento** [comment]
True, you can specify which folder? If you mean the pictures of the devices you can only keep the photos that you use and eliminate everything else but it is a job that you should do on your project because depending on the type of project everyone can use a mock-up of the device that he prefers
